### ISSUE TITLE
Error Loading Module

### ISSUE THREAD

**Issue by Eddiedash** [kaijxc/TT2B#1]
error loading module 'TT2.tt2utils' from file '/var/mobile/Library/AutoTouch/Scripts/TT2/tt2utils.lua':/var/mobile/Library/AutoTouch/Scripts/TT2/tt2utils.lua:400: 'then' expected near 'local'

**Comment by kaijxc** [comment]
Thanks for the headsup, made this fix on device and it never made it to the repo. Cheers!
